[package]
name = "rustle"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.4"
colored = "2.0.0"
dirs = "1.0.4"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
